name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  linux-build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
      
    - name: Upload AppImage
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: "**/EternalResourceExtractor.AppImage"
        tag: ${{ github.ref }}
      
  windows-build:
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
      
    - name: Upload Exe
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: "**/EternalModManager.exe"
        tag: ${{ github.ref }}
    
